### ISSUE TITLE
Skip injecting the CodeQL workflow if the action is Docker based

### ISSUE THREAD

**Issue by rajbos** [rajbos/github-actions-requests#12]
If `action.yaml` is running a Docker image, we need to skip the CodeQL workflow since that will fail (because there is no code to be found).

Syntax:
```` yaml
runs:
  using: docker
  image: Dockerfile
````
